### ISSUE TITLE
Error connecting to RPC

### ISSUE THREAD

**Issue by axcc1** [DorianKucharski/easybitcoinrpc#2]
Hi, i've some issue connecting to local RPC:

```
Traceback (most recent call last):
  File "C:\Users\axus3\PycharmProjects\hash\utxo.py", line 6, in <module>
    block = rpc.blockchain.get_best_block()
  File "C:\Users\axus3\PycharmProjects\FTX\venv\lib\site-packages\easybitcoinrpc\blockchain.py", line 29, in get_best_block
    best_block_hash = self.__rpc.batch(["getbestblockhash"])
  File "C:\Users\axus3\PycharmProjects\FTX\venv\lib\site-packages\easybitcoinrpc\rpc.py", line 32, in batch
    return self.__rpc.batch_([command])[0]
  File "C:\Users\axus3\PycharmProjects\FTX\venv\lib\site-packages\bitcoinrpc\authproxy.py", line 167, in batch_
    responses = self._get_response()
  File "C:\Users\axus3\PycharmProjects\FTX\venv\lib\site-packages\bitcoinrpc\authproxy.py", line 186, in _get_response
    raise JSONRPCException({
bitcoinrpc.authproxy.JSONRPCException: -342: non-JSON HTTP response with '401 Unauthorized' from server

Process finished with exit code 1
```

here my code:
```

from easybitcoinrpc import RPC

rpc = RPC(ip="127.0.0.1", port=8332, user="user", password="password")

block = rpc.blockchain.get_best_block()
```

here my bitcoin.conf:

```
rpcpassword=password
rpcusername=user
rpcallowip = 127.0.0.1
rpcport = 8332
listen=1
rest=1
daemon=1
server=1
rpcbind= 127.0.0.1
bind = 127.0.0.1
```

already try connect with/without user:password, but still have issue, any idea?

**Comment by axcc1** [comment]
I just find out the problem:

i just need to lauch bitcoinqt with theses args:
-server=1 -rpcuser=user -rpcpassword=password

it seems that the pw and user of the bitcoin.conf file are not used (they are well load, that i can see in the log at launch)
